### DISCUSSION TITLE
access whole command list

### DISCUSSION THREAD

**Discussion by iancote** [python-cmd2/cmd2#1129] [Q&A] [answered]
Hello!

So I have a use case where I'm trying to build a cli configuration tool to eventually create a yaml file.  I'd like to have the options the user enters autocomplete and eventually store in a dict I'm maintaining for dumping to said yaml.  I was looking to use the arg_tokens feature like this:

Pass a dict of dicts structure like this or similar to a completer function:

```
subcommand_option1:
  field1:
    - a
    - b
    - c
  field2: 
    - c
    - d
  field3:
    field3_suboption1:
      - e
      - f
    field3_suboption2:
      - g
      - h

```
Then I'd like to return completion items to let them tab complete/ get description text for things to eventually get a line like
subcommand_option1 field2 c
that I can render back into yaml like:
subcommand_option1:
   field2: c

I'm getting stuck in that I see the line in cmd2_statement.get(), but it's just a string so I can parse that, but I wonder if there's a better way to do all this?  I feel like I'm recreating a wheel here.

Any help or suggestions appreciated.
